### ISSUE TITLE
Feature request: chart right margin offset setting

### ISSUE THREAD

**Issue by TimoJJ** [alexarch21/history-explorer-card#102]
Feature request: add a parameter that allows to adjust the time offset from chart's right margin. Currently chart's right edge/side is the current value/time but I’d like to have there some user adjustable time, maybe a percentage value based on the displayed time scale or just minutes/hours. Both line and bar graphs.
And maybe add an optional last measurement point marker with selectable color e.g. red dot for line type charts.

Attached example pictures: original, with offset, offset with marker.
.
![chart1](https://user-images.githubusercontent.com/63199895/206392958-97939ca3-1e47-4a5b-a737-7abb2431e296.png)
![chart2](https://user-images.githubusercontent.com/63199895/206392962-bbc60654-d862-4c34-be6a-eb00bc605dc9.png)
![chart3](https://user-images.githubusercontent.com/63199895/206392964-41aa1861-a49c-43d1-aa6d-aaa7ac73d737.png)

**Comment by itspt1** [comment]
This feature would be ideal. Specially for consumption entities.
Ideally the offset can be defined in hours. 
I don't think the graph should necessarily show the blank space until the current time. 

In my use case I'd like to show the energy consumption only until yesterday. Since the today's consumption changes continuously.

**Comment by alexarch21** [comment]
> I don't think the graph should necessarily show the blank space until the current time.
In my use case I'd like to show the energy consumption only until yesterday.

Could you clarify what exactly you mean by this ?

**Comment by itspt1** [comment]
@alexarch21 
I think my comment differs from what @TimoJJ was requesting.

What I meant was, only being able to navigate within the defaultTimeRange.
For example: defaultTimeRange 7d, then the user can only "explore" that time frame and not go further/back in time.
Ideally the user could define an offset, so that the 7 days begin yesterday. Or a month ago.

Currently my HA recorder has the default keep_days value of 10. Therefore navigating more than 10 days ago only shows an empty graph. The same in the other way (future).

I know this (empty graph) doesn't affect functionality but, in my opinion, from an UX viewpoint it'd be a nice detail.
Again, this topic might be something completely different so I'd open a new FR if it's something that makes sense for you.

**Comment by alexarch21** [comment]
Yeah, this is an entirely different thing. I'm not sure if intentionally restricting functionality is really desirable, but let's see if more people are interested in this. Note that data doesn't necessarily end beyond the purge day period, as long term statistics may be available too (if enabled in the card settings). In that case, you can explore back a lot more.

**Comment by alexarch21** [comment]
Custom time offsets are now supported in V1.0.42. [See here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/591) for more info.
