### ISSUE TITLE
FR: Option to exclude specific entities when automatically setting the y-axis scale

### ISSUE THREAD

**Issue by robertwigley** [alexarch21/history-explorer-card#113]
There are certain entities I want to include in the card, but I don't want to be taken into account when the y-axis scale is automatically determined by the integration. Is there any chance an new option could be added that could list entities to exclude when the integration is determining the scale automatically itself?

**Comment by alexarch21** [comment]
Complicated, that would require deep modifications inside the graph renderer. All entities belonging to a single graph aggregate their data into a single big data stream basically. Y axis determination is performed on this aggregated stream.

What exactly is your use case ? There might be other ways to approach things.

**Comment by robertwigley** [comment]
I have a template sensor that mimics the heating part of the built in `History Graph Card`.

```
- sensor:
    # Living Room Heating Graph sensor
    - name: Living Room Heating Graph
      icon: >-
        {%- if is_state('binary_sensor.living_room_heating', 'on') -%}
          mdi:radiator
        {%- else -%}
          mdi:radiator-disabled
        {%- endif -%}
      state: >-
        {%- if is_state('binary_sensor.living_room_heating', 'on') -%}
          {{ states('sensor.living_room_climate_temperature') }}
        {%- else -%}
          0
        {%- endif -%}
```

![image](https://user-images.githubusercontent.com/12278920/208303108-6fd34468-17e4-4a35-a441-55c58589f7d1.png)

As the minimum will always be 0, I want to exclude it from the calculation for automatically setting the y-axis scale. I know we can set the y-axis scale manually, but the outside temperature varies during the year, so really want it to be dynamic if possible.

Maybe another approach/option would be to allow templating of the y-axis option? That would be super-flexible.

**Comment by alexarch21** [comment]
OK, it's for the heating thing. There have been a few discussions on how to achieve this best.

> Maybe another approach/option would be to allow templating of the y-axis options? 

That doesn't work. ymin/max are values that are computed by aggregation on historical data sets, not from a single value in time. These datasets need to be fetched from the database, cached, etc, before being accessible. Allowing the random access to an entity state from a user defined function would require massive changes to the underlying entity DB caching system. And even if I did that, it would still not work, because we're back to the point I mentioned above: ymin/max are *aggregate* properties calculated from *all* datasets in the graph. You can't just pick or exclude one.

I think this heating on/off thing is a very specific use case that needs to be addressed as such and not through workarounds. There have been some discussions around it [here on the HA forums](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/551) on how this could look like. Feel free to chime in.

**Comment by alexarch21** [comment]
I did some tried. Instead of setting the heating graph sensor to numeric value of `0` when the heating is off, did you try setting it to the string `'undefined'` instead ? That may give you what you want.

**Comment by robertwigley** [comment]
Thanks. Sorry for the late reply. I had to wait for the data to feed through the system, but that seems to work. Thank you.
