### ISSUE TITLE
Add a refresh button 

### ISSUE THREAD

**Issue by joewashear007** [alexarch21/history-explorer-card#127]
I saw in #4 that auto updating the graphs is not implemented yet, but I was curious how challenging it would be to add a manual refresh button to graphs. 

I have some graphs that I will keep running on dashboard that check periodically and I would like to be able to not refresh the who page. Either that or is there a manual way to reload the whole Lovelace card?

Thanks!
Joseph

**Comment by joewashear007** [comment]
That would be awesome to add and a much appreciated feature!

Thanks for all you great work!
*Joseph Livecchi*

**Comment by prof7bit** [comment]
Maybe until proper auto refresh is implemented you could add an option to the drop-down menu, or maybe something like refresh with double- or triple-tap on a graph.

This is a serious issue, in the android companion app there exists no way to refresh a dashboard (like there is F5 on the PC), they omitted this intentionally because they classify any card that cannot update on its own (automatically!) to a bug in the card and should be fixed there.

So this is not a feature request, this is an outright bug and should be priorized as such.

**Comment by alexarch21** [comment]
Automatic (configurable and optional) refresh is in the next release. It already works here on my dev build and I use it all the time myself since. It's very convenient. It will, however, not be enabled by default. At least for the time being.

The companion app not offering refresh is a design flaw. There's a reason all browser do offer this.

**Comment by alexarch21** [comment]
Auto refresh options were added to V1.0.43. See readme under [auto refresh](https://github.com/alexarch21/history-explorer-card#auto-refresh) for more details.

**Comment by prof7bit** [comment]
Great! 

This seems to be working perfectly!

But one thing I don't understand: In the documentation you write that you monitor all relevant events to get updates but then further down you write that fast changing entities would strain the database bandwidth and updates in intervals would be better in that case. The thing I don't understand is this: If you update the entire graph in regular intervals you have to query at least all the states that have happened since the last updates, but if you apply the state changes as they come streaming in you don't have to query the database at all. So my intuitive assumption would be that querying the database would cause more traffic than just appending the changes as they come streaming in. Where is the error in my thinking?

**Comment by alexarch21** [comment]
There will always be a db request, even for monitored entities (not for every single change, requests are batched with a minimum granularity of 2 seconds). The card will not just append the data om its own. The HA recorder component does some processing with the data before writing it to the db, specifically for total increasing entities and timezone related on the last changed field.

These requests will typically not result in actual physical db accesses, they're cached by the db engine. Still, too many of them will strain the host cpu, especially on sbc.
