### ISSUE TITLE
Feature: Manage attributes (climate entities)

### ISSUE THREAD

**Issue by chrispazz** [alexarch21/history-explorer-card#144]
Hello, is it possible to manage also state_attr like built-in history card do with climate sensors (adding target temperature, current temperature and state on/off)?

Thank you

**Comment by alexarch21** [comment]
No, not directly. Attributes are not supported at this time, mostly due to performance reasons. You can however use template sensors to create entities out of your attributes and graph those instead.

For reference, it is better to ask questions like these on the [HA forum thread here](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450). Then the community can also answer. The github is more about bugs and FRs. Thanks !
