### ISSUE TITLE
Export with Add Entries disabled

### ISSUE THREAD

**Issue by dwschmid** [alexarch21/history-explorer-card#145]
I would like to disable the possibility to add entries but keep the option to Export as CSV. Is this possible? I know I can deactivate the entire selector part with the code below, but don't know how to control the sub-parts individually.
```
uiLayout:
  selector: hide
```

**Comment by alexarch21** [comment]
You can't hide part of the selector separately, at least not through card options. You could use something like card-mod to hide the individual components I guess.

**Comment by dwschmid** [comment]
Thanks for the quick reply!
I'll have a look. I still think it would be a useful feature to have them
separate. Data Export is always useful while the possibility to add
additional entities less so (for me, I understand use cases are different).

Thanks for the excellent work!

**Comment by alexarch21** [comment]
I tend to disagree that allowing config to separate them would be generally useful, besides the fact that adding this would make the UI quite a bit more complex to maintain in the long run (all UI layout toggle permutations do). Of course the best option would be a completely separate dot-style menu for dropdown options. But then people will start asking for toggles on that and on custom placement options and custom sizes and custom colors, etc :) It's very hard to please everyone on UI matters because it's so subjective and all use cases are different.

But in the end that's what card-mod is perfect for, customizing things for unique situations.
