### ISSUE TITLE
Settings not synchronised across devices / applications

### ISSUE THREAD

**Issue by StephaneStolz** [alexarch21/history-explorer-card#146]
I setup the contents of the history explorer card by choosing which sensors should be displayed in the card on my desktop, using the internet browser (chrome).
When I use the companion app on the same desktop, none of my selection is shown on the app.

Similarly, if I visualise the same card on my iPhone or on my Google display, none of the selection is shown.

This is an issue as I cannot effectively setup the card for other users to see, as they have to setup the card themselves.

It seems that the contents of the card is saved on client-side cookies rather than server-side configuration.

**Comment by alexarch21** [comment]
The config for dynamically added sensors is stored client side, there is no other technical way (HA does not allow server side storage for frontend cards). So that is by design and unavoidable. If you want sync'ed cards on multiple devices, then define the graphs manually in the cards configuration YAML. It's all described in the readme.

**Comment by StephaneStolz** [comment]
Thank you for the prompt response and the explanation.
I will close the issue then.
