### ISSUE TITLE
Contact Request

### ISSUE THREAD

**Issue by adamish717** [alexarch21/history-explorer-card#147]
Hi Alex, your card has come closer to what I'm looking for than anything else I've found.

How many coffees would I have to buy you to see if this card is able to do what I'm looking for?

I have remote android devices that are reporting their RX/TX data usage.

I want a card where I can select the date-range, and it will give me the difference in value between the beginning and end of that date range (which would be the total data usage for that range).

Willing to pay, because nobody seems to have any idea how to do this!

Adamish#6662 on the official HASS discord

**Comment by adamish717** [comment]
If any other HASS front-end devs are interested, you can also contact me.

**Comment by alexarch21** [comment]
If your tx/rx data usage sensor is a total_increasing sensor, ie if it represents the total accumulated data usage over time, then you can use this card to show data usage per period (every 10 minutes, hour, day, month) as bar graphs (see the [readme here](https://github.com/alexarch21/history-explorer-card#bar-graphs-for-total-increasing-entities)). 

If the sensor reports instant usage instead of accumulated, then you need to calculate total usage over time first by evaluating the area below the signal over time, for example with a Riemann sum integral. I think HA has a corresponding integration for that. The result can then be used by this card to show usage per period, as above.

Custom ranges are not supported by this card, as this wouldn't make much sensor with a graphing card. This card also doesn't calculate the integral of instantaneous sensors as this would be out of scope for a graphing card.

If you just need to display total usage for a given data range from historical data, I'd be very surprised if there wasn't a custom card somewhere already doing this. It's super trivial, maybe a few dozen lines of code, something that could probably be thrown together in a couple of hours. But as said, I'm afraid this is out of scope for the history explorer card.

**Comment by adamish717** [comment]
Thanks for the clear answer @alexarch21

Even with total_increasing, the History Explorer card still shows the daily usage, rather than the total of accumulated data (and still not giving "total data used per given period").

Are you undertaking paid work these days? I would certainly be interested in buying a few hours of your time!!

![Screenshot_1](https://user-images.githubusercontent.com/3332843/221096389-a5be2ead-8871-4052-8a9e-f37129610446.jpg)

**Comment by alexarch21** [comment]
> Even with total_increasing, the History Explorer card still shows the daily usage, rather than the total of accumulated data (and still not giving "total data used per given period").

It shows the total amount of data used per given period you selected in the dropdown (per day, hour, month, etc).

> rather than the total of accumulated data

What do you mean by that ? If you want to show the raw total accumulated value, you need to use a line graph instead.

> Are you undertaking paid work these days? 

I'm afraid not.

**Comment by adamish717** [comment]
Oh you're totally right, that looks much better! A graph moving ever-upwards now!

We might actually be able to work with this.

If the device uses 7gb of data per week, and has been collecting data for 3 weeks, it will show 21gb on "today". If I show the last week, it will give me "14gb - 21gb" for that period.

Is there a way to tell the card to give the first value as a 0-starting point, counting up from there? Doing the math isn't difficult from our end, but we'll have 30 mobile devices on here, and that's a lot of manual math by hovering over line graphs.

**Comment by alexarch21** [comment]
> Is there a way to tell the card to give the first value as a 0-starting point, counting up from there?

Not natively. While this is an interesting feature for sure, it should be a separate component. It's not really in scope for this card, as this is not a graphing problem. It's for displaying a value evaluated from historical data. There might already be something available that does this (I would be surprised if there wasn't). It's basically two database accesses, a subtraction and some boilerplate code to display it in a card.

If the custom time range is always the same you could even use an automation to do this.

**Comment by alexarch21** [comment]
I'm going to close this, as it isn't really related to the history explorer card.

**Comment by adamish717** [comment]
Sorry, for sure. I appreciate the support, and it pointed me in the right direction!
