### ISSUE TITLE
Table proposal 

### ISSUE THREAD

**Issue by PawelTolo** [alexarch21/history-explorer-card#148]
Hi Alex, 

Is it possible to create table like the one i attached  ? 
![alex](https://user-images.githubusercontent.com/106479579/221121232-b05bed29-b4b7-46b2-9b4e-51e601605285.JPG)

**Comment by alexarch21** [comment]
You'll have to create that table in Excel. The History Explorer card only exports the raw data into a basic table. You should use Excel to process and format the data. Adding custom table formatting into the card would be a huge amount of work, due to the myriads of ways these things can be layed out and configured.
