### ISSUE TITLE
axisAddMarginMin not working with negative values

### ISSUE THREAD

**Issue by sky-jreves** [alexarch21/history-explorer-card#157]
Hi.
Thank you for your job building this component, I think it is amazing.
It seems there's an issue when using the `axisAddMarginMin` property in a range that include negative values.
In this example I have it like this `axisAddMarginMin: false` but it is still including a margin on the lower bound of the Y-axis as can be seen in this image:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/20165858/223970438-739884f4-3b2c-4226-9055-88c37e6749cd.png">

**Comment by alexarch21** [comment]
That's not from `axisAddMarginMin`. If that setting is set to false, then it's just off, regardless of the data range. What you're seeing is just the normal y-axis scaling done by the charting engine. Your data becomes slightly negative at some point, so the scale is adjusted to reflect this. `axisAddMarginMin` creates problems only when your data doesn't become negative (it stays at 0). Actually `axisAddMarginMin` is disabled by default since V 1.0.43 and I might remove it entirely from upcoming versions.

How do you see your y-axis look like for data like this ? There are negative parts after all. And keep in mind that the positive and negative parts of the y-axis need to be symmetrical. If you don't want a negative scale to appear at all, then for `ymin` to 0, that will effectively cut out everything negative.

**Comment by sky-jreves** [comment]
> That's not from `axisAddMarginMin`. If that setting is set to false, then it's just off, regardless of the data range. What you're seeing is just the normal y-axis scaling done by the charting engine. Your data becomes slightly negative at some point, so the scale is adjusted to reflect this. `axisAddMarginMin` creates problems only when your data doesn't become negative (it stays at 0). Actually `axisAddMarginMin` is disabled by default since V 1.0.43 and I might remove it entirely from upcoming versions.
> 
> How do you see your y-axis look like for data like this ? There are negative parts after all. And keep in mind that the positive and negative parts of the y-axis need to be symmetrical. If you don't want a negative scale to appear at all, then force it with `ymin` set to 0, that will effectively cut out everything negative.

Hum so I dind't understand well the expected behaviour for axisAddMarginMin.
I think I can achieve what I need with ymin (although this doesn't seem to be documented), but this way my range will not be dynamic according the values present.
I was expecting that the graphic didn't add unnecessary margin to values present like the following
<img width="370" alt="image" src="https://user-images.githubusercontent.com/20165858/224332342-957e19ac-63ca-4500-8270-0ec85f568ddd.png">

How it is right now it's decreasing a useful area of the graphic and losing resolution to the values shown.

**Comment by alexarch21** [comment]
AxisAddMargin was mostly designed to make room for a curve 'overshooting' into areas above or below the valid range of data. This happens very rarely, it's much more uncommon than originally anticipated and it only happens with spline curve graphs. As such that feature is not very useful and has been disabled by default.

The charting renderer will choose a scale that fits the data and that looks nice. For that it generates the Y ticks so that the tick spacing is even, whenever possible. Specifically it will try to avoid situations like the one in your example (the squashed -0.02 to -0.03 at the bottom). Instead it will create more space for negative values and keep things nice and symmetric. It's a tradeoff.

Use ymin/ymax if you want to limit the range. You will find several usage examples for those in the sample YAML in the readme.
