### ISSUE TITLE
Support for attributes

### ISSUE THREAD

**Issue by dodekaphilist** [alexarch21/history-explorer-card#16]
It looks like it's currently not possible to add an attribute of an entity to the graph. Would be really nice, if the card could support this as I would like to compare multiple values that are not entities themselves. Thanks! 🙂

**Comment by alexarch21** [comment]
It's complicated. Basically it comes down to performance. Supporting attributes, as nice as it may be, would incur a hard performance toll on the card which would also affect all other graphs that don't show attributes. That's from the way the HA recorder manages the database internally. There are (hacky) ways around this somewhat, but they would make the card code considerably more complex and hard to maintain.

Here's some more info from my post on the HA forums:
https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/87

Due to these technical limitations, at this time I won't implement this sadly. But I will keep an eye on the option, maybe some future HA version will make this more efficient. In the meantime, you can always use a template sensor to map an attribute into its own state entity that can then be displayed.

**Comment by dodekaphilist** [comment]
Thanks for your reply. I understand the technical issues related to this change, so I think it's the best to put it on the back burner for now.
The workaround with templates sensors is a great interim solution, I didn't think of before, thanks!
