### ISSUE TITLE
FR: In tooltip for text based sensors, wrap text to multiple lines when too long.

### ISSUE THREAD

**Issue by lizaoreo** [alexarch21/history-explorer-card#167]
Pretty much as the title says, I have some text based sensors that sometimes have text that's too long for the tooltip so it goes off screen since the toolbox is limited to the size of the graph window basically.  It would be nice if it would either automatically wrap text to a new line after so much, or had a configured number of characters it would display before wrapping.

**Comment by alexarch21** [comment]
That would require the popup tooltips to be converted to html elements first (and it would be a implicit sideeffect to this conversion). Doing this conversion is planned at some point, as it would fix some other long standing issues, but due to the required time investment for this change, it's not the highest priority right now.

**Comment by lizaoreo** [comment]
Sounds good, and yeah, that would be a bit more of an overhaul.  I'll mark as closed since the root cure is it's own separate planned project already.
