### ISSUE TITLE
FR:  Scale Y-axis to data shown in TimeRange

### ISSUE THREAD

**Issue by icepop456** [alexarch21/history-explorer-card#173]
I would like to set the y min/max based on data displayed.   I would be ok with the axis moving around while scrolling, but I would not think it is very common to scroll rapidly/frequently to make it look "chaotic".  

The 24 hour looks like this (pool temperature drops to ambient as I have a sensor in a pipe and it drops when the pump is off)

![image](https://github.com/alexarch21/history-explorer-card/assets/77653506/bcd01028-f9fb-460c-81d7-94dae4e3baee)

When I zoom in to a ~6 hour window, the Y is blown out and it is not user friendly on an iPhone to get a relevant axis.  

![image](https://github.com/alexarch21/history-explorer-card/assets/77653506/cc3c833a-3b59-4648-814e-95cdca262fac)

This is ApexCharts lets you define min/max based on data and it works really well:

>  min: '|-1|'
> max: '|+1|'

Scale to data button would work as well, but idealy we can set a flag to always scale to view.

**Comment by alexarch21** [comment]
> I would like to set the y min/max based on data displayed. 

That's what the card does by default (unless you explicitly override the the ymin/max in the yaml). There is a time range filter applied to the auto adjustments, so that the adjustment is done over a larger time scale while you scroll rather than instantly changing the scale. This is done on purpose.

> but I would not think it is very common to scroll rapidly/frequently to make it look "chaotic".

This is exactly the problem of instant auto adjustment. Rapid scrolling is pretty much the norm amongst most users (including myself). Instant auto adjust gets so chaotic that the card becomes unusable when you scroll. Thus a time range filter was added to the auto adjust.

You can use [interactive Y axis scrolling](https://github.com/alexarch21/history-explorer-card#y-axis-scaling) if you want to zoom into an area on the Y axis (although this feature is currently limited on a touch screen).

**Comment by icepop456** [comment]
Fair enough.  I could really use Y-axis scaling  on range filter selection and not the 24 hour it does today.  The mobile usage is what hurts me the most.   

Maybe let us live dangerously with rapid scrolling?  I'm used it with Yahoo Finance and other stock charts.  Feels somewhat natural to me.

**Comment by alexarch21** [comment]
This was a design decision made after playing around a lot with various autoscale filters (including no filter at all) and this was the best compromise. Smooth continuity of signal that you can easily follow visually while scrolling was deemed more important than immediate rescaling. To be honest, this is unlikely to change. It's all about compromise.

Interactive Y axis scaling makes this mostly a moot point anyway. Just zoom onto things of interest. Making this part easier on mobile is on the roadmap.

**Comment by icepop456** [comment]
Ok thanks
