### ISSUE TITLE
Display attributes history

### ISSUE THREAD

**Issue by fredck** [alexarch21/history-explorer-card#212]
There should be a a way to select attributes inside entities to be used as data for the history charts. 

An existing use case is the default history of "climate" entities:

<img width="920" alt="image" src="https://github.com/alexarch21/history-explorer-card/assets/630060/d7ec211b-a7e4-4a27-bc6f-1654ca6a31d3">

As we can see, the entity "state" is not even considered in the graphs but instead 3 of its attributes:
 - current_temperature
 - temperature... presented as target temperature
 - hvac_action...  presented as "heating" which is actually a filtered value of the "hvac_action" attribute so other values are not even included in the graph

The above is a powerful history plotting, which is essential to analise the implementation and performance of thermostats in ha.

I've found and installed this addon exactly with the hope of having a richer solution for the above chart.

**Comment by alexarch21** [comment]
Due to the way the HA recorder handles attributes, it is not possible to add attribute support while keeping a good interactive performance while streaming the DB in realtime. It is not planned to add attribute support to this card in the foreseeable future.

As a workaround you can use a template to copy the needed attributes into the their own entity and graph that.
