### ISSUE TITLE
Label goes off the edge of the card

### ISSUE THREAD

**Issue by mdegat01** [alexarch21/history-explorer-card#28]
First of all, really liking this card. I primarily use history for debugging to see what state relevant things were in when something broke. This is exactly what I was looking for, I always have like 4 tabs open just to see different entities at the same time. Easily being able to put them all stacked with highlight and zoom capability is just phenomenal. And really smooth, well done!

Only small issue is my labels seem to be running off the side of the card. Makes it a bit difficult to determine which graph is for what when there's a bunch:

![Screen Shot 2022-04-01 at 7 46 30 PM](https://user-images.githubusercontent.com/2037026/161355123-3761304a-148b-4ae3-a211-ec4b1c1cbf8e.png)

My tech specs for reference:
MacOS Monterey 12.2.1
Firefox 98.0.2
HA version core-2022.4.0b1

**Comment by alexarch21** [comment]
You can make the label area larger with the `labelAreaWidth` option. See the Readme under [Changing the ui layout](https://github.com/alexarch21/history-explorer-card#changing-the-ui-layout). Value is in pixels, default is 65.

**Comment by mdegat01** [comment]
oh ok, I assumed it would automatically make it fit. that works though

**Comment by alexarch21** [comment]
Doing it automatically is problematic. One long label would have to push everything out, all other graphs in the card, because they need to be kept in sync visually (like your 10pm line should be at the same pixel location throughout all graphs, so that all 10pm ticks from all graphs are aligned along a common vertical line). That would create a lot of empty wasted white space on the left. I figured that the occasional clipped entity name was the lesser evil.
