### ISSUE TITLE
Graph gaps

### ISSUE THREAD

**Issue by emufan** [alexarch21/history-explorer-card#3]
At first: Brilliant card!

Du you have any clue, why there are gaps with this cards?

![image](https://user-images.githubusercontent.com/22775515/149175907-f78102de-7b74-4f46-9afc-a4f776e69d74.png)

vs

![image](https://user-images.githubusercontent.com/22775515/149176073-9b401143-9590-4826-9a2c-54b122d6a9ed.png)

Tried it with every curve types, etc. Always the same gaps.

**Comment by alexarch21** [comment]
Hey thanks !

Usually that means there was no information available in the database during these time periods. Maybe you restarted HA ? This will create gaps like that, often longer than the time HA was offline. Or maybe the sensor went offline for a while and came back later ? The HA built-in history will often just connect these 'dead' parts with lines hiding them (depending whether the entity state became unknown or unavailable during that time). The history explorer card doesn't, on purpose. Because if there's nothing in the history, it should show that. That way you can identify problems and drop outs for sensors.

**Comment by emufan** [comment]
Might be. Have to have a deeper look. But currently the time frames seem to me to long for this. What does no data mean? I would think that between two data points there is always a gap. Longer or shorter. 

Do you think that you will introduce an option to switch on a gap smoothing at some point in the future? I like the approach, that you have described to be able to see gaps.  But sometimes I would like to use it with closed gaps.

**Comment by alexarch21** [comment]
No data means that an item is in the database with an unavailable or unknown state. If that happens the line/curve just before and just after this item won't appear. Depending on how far the last or next entries are from the unavailable state, the gap can be pretty long. Keep in mind that the database only stores state changes.

I guess I can add an option to interpolate over them on the next release. It would have to be enabled in the yaml (default would be off).

**Comment by emufan** [comment]
> No data means that an item is in the database with an unavailable or unknown state.

Ah. Was not aware. Thought, that there is only "no data". Understood.

> I guess I can add an option to interpolate over them on the next release. It would have to be enabled in the yaml (default would be off).

Great. I had this in mind. default off and only a yaml option as for the decimation. Idea: Per entity and not per card. Or both, global and local for overruling. As said, not time critical. Thanks so much.

**Comment by alexarch21** [comment]
Option to hide gaps was added in v1.0.9. See readme for usage details. Only a global option is available at this time.

This will only hide gaps due to unavailable data, like for example from offline devices or HA restarts. Gaps can still happen at the beginning of the graph when the state was unchanged for multiple days before. Zooming out or panning the graph will usually fix this. That's due to a bug / limitation in the HA database engine. The HA history panel is also affected by this.
