### ISSUE TITLE
Card shows incomplete history

### ISSUE THREAD

**Issue by RogerSelwyn** [alexarch21/history-explorer-card#31]
When I access the card for the initially it shows incomplete statuses, or at least it seems to shows statuses that have changed since the start of the displayed period, see below. Where they all show in a line down the right hand side is when I last restarted HA. If the graph is viewed after 12 hours (because that is my default viewing period) from the last HA restart, it will show correctly all the time. This has only occurred since the 2022.4 release, so I'm sure is related to the changes in how data is stored in that release.

<img width="2292" alt="Screenshot 2022-04-09 at 13 22 12" src="https://user-images.githubusercontent.com/7115783/162573987-eeb64b35-774b-4c47-95e1-387bd7de3797.png">

If I then zoom out to 1 day, then back to 12 hours, they show correctly as below.

<img width="2298" alt="Screenshot 2022-04-09 at 13 23 27" src="https://user-images.githubusercontent.com/7115783/162574024-4a1b5526-caa9-4db6-8e85-146af97b8dca.png">

<img width="2286" alt="Screenshot 2022-04-09 at 13 23 41" src="https://user-images.githubusercontent.com/7115783/162574027-6c871caa-d183-471e-b5c0-a44f583fbe8e.png">

There also seems to be a similar issue with the built in HA History card, but with that I can't get it to show correctly unless the time period is corrected to the after the last HA restart.

**Comment by alexarch21** [comment]
Yeah that's a limitation of the HA recorder component, in simplfied terms, it has to do with the way the recorder only stores state changes and does not correctly report them when they happened before the requested time period.

You can usually make the data appear by scrolling left (or zooming out) and then back right. It's unlikely that it is related to the changes in 2022.4, it's probably just because you happened to have restarted HA for the update. I currently have a beta build with some changes that make it a little better, but it won't entirely fix it.

See [this reply on the HA forums](https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/166) and the following couple for some more technical info.

**Comment by alexarch21** [comment]
Reopening this for tracking this issue. Some additional tests show that this behavior is indeed much worse in 2022.4, because what looks like a bug in the HA recorder component that was introduced in 2022.4. It might also be an artifact of the database migration, so we will have to wait a few days for enough new data to be recorded using the new db format.

If this persists with new data too, then this will have to be reported as a bug in the recorder component.

FWIW, the native HA history panel is affected the same way.

**Comment by RogerSelwyn** [comment]
I upgraded to 2022.4 in one instance on Wednesday, and the other on Friday. Over a period of time from HA restart the problem disappears. At restart the issue shows again. For me this became very clear with 2022.4. To be honest I restart pretty often, primarily because I support three integrations (O365/SkyQ/SkyQ Hub), so I'm pretty sure I would have spotted it if it was as visible as it is now before the upgrade.

**Comment by alexarch21** [comment]
This issue seems to resolve itself on new data recorded in the db using the new format. The problem seemed to be limited to the part of the db that were migrated from the old to the new format.
