### ISSUE TITLE
Grid formatting

### ISSUE THREAD

**Issue by Eckart0** [alexarch21/history-explorer-card#35]
Hello,
I have a suggestion: I often use history-explorer-card to display only one timeline in the most space-saving way.
It would be nice if the stored time grid were less high in this case. With only one timeline, the grid extends far above and below the timeline. I have not made any progress with card-mod.
Many greetings, Eckart
![220416 history_card](https://user-images.githubusercontent.com/29716849/163683112-546ad489-305b-4e03-a947-b90c0a432830.png)

**Comment by alexarch21** [comment]
The reason for this is so that the tooltip popup fits on the graph canvas. If there's not enough vertical space, the tooltip will be clipped. It can't go outside of the graph, since it's not an html element.

You can reduce the size of the tooltip popup to slim, that will make single timeline graphs narrower. Maybe not as much as you suggested, but quite a bit still.

`tooltipSize: slim`

[See here](https://github.com/alexarch21/history-explorer-card#configuring-the-tooltip-popup)
