### ISSUE TITLE
Increase max history readout (1 month)

### ISSUE THREAD

**Issue by voarsh2** [alexarch21/history-explorer-card#56]
Useful tool.

I am using it to export power readings for my machines and have a dispute that requires me to export more than 1 month of data.
I was wondering if this could be possible to implement? Custom range?

Thanks.

**Comment by alexarch21** [comment]
Not easily without implementing new UI specifically around this, something I'd like to avoid. Considering that it is very uncommon for people to have a native HA database with a month or more worth of data. Typically people will use external databases like influx to store long term data instead.

**Comment by voarsh2** [comment]
Ah, yes, you're right. I did look into influxdb but it required some time and setup that I'd need to look into more.
And I wouldn't have a way to preserve the existing data in HA. Do you know if existing data could be pushed to Influx or if it's just new data?

**Comment by alexarch21** [comment]
HA's native DB is an SQL database, so you could extract the data using SQL queries operating directly on the DB. The table structure and data encoding HA uses is a little weird though and will need some converting and adjusting.

Is this entire DB exporting a one-off thing you need or is this a regular use case for you ? If it's a one off thing, you could hack this into the source of the history explorer card, so the CSV export would dump the entire history for an entity rather than just what is shown.
