### ISSUE TITLE
Wrong date format for portuguese

### ISSUE THREAD

**Issue by usernein** [alexarch21/history-explorer-card#58]
I didn't get why, but the date format is broken when i use HASS in Portuguese, either pt or pt_br

I tried some other languages and only found this issue on Portuguese
I tried changing the number format and the hour format but nothing changed

<img width="394" alt="Captura de Tela 2022-09-02 às 10 55 53" src="https://user-images.githubusercontent.com/29507335/188166032-92b486fe-bfbb-44ca-8f42-9baaf68b9bab.png">

**Comment by alexarch21** [comment]
The reason is that the date format returned by the browser seems very different in Portuguese than for any other language I tried. For other languages, the short format date would look something like _2 Sep 2022_ or _2.09.2022_. Days, months and year are separated by symbols like spaces, dots, dashes, etc.

In Portuguese, the date string looks like this: _2 de set. de 2022_. And the parser is not able to process this correctly, because there are additional words appearing in the string.

I'll see how I can fix this.

**Comment by alexarch21** [comment]
Should be fixed in V1.0.25.
