### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GrizzlyAK** [alexarch21/history-explorer-card#60]
I found this excellent piece of work while looking for a replacement for the lost History panel functionality removed in 2022.8. Is there a plan to have an option to read the **recorder.yaml** file and use that entities list and assign random colors, which would likely be a replacement for (and better solution than) what HA provided before. I'm exploring your card now and it is pretty awesome!

**Comment by alexarch21** [comment]
Thanks, glad you like the card !

It's not technically possible for a client side card (which is Javascript code running locally on the device you view the page with) to read any YAMLs or other local files on the server I'm afraid. Doing this would require developing an entirely new custom integration running on the server, rather than just a custom card.

Is there a specific reason you want to use a separate YAML file over the YAML card configuration ?

**Comment by GrizzlyAK** [comment]
Hi Alex,

Oh, yeah, that makes perfect sense. I totally spaced where this code was running. I have yet to adequately figure out the architecture of HA (and may never!).

There is no _good_ reason to choose recorder.yaml over the card config other than I know there are many of us who are disappointed that the HA devs removed any option to maintain the previous display option, i.e., based upon the recorder.yaml file. We all have that set up like we want it, and it is no longer even considered for History. We used the previous History panel as a "glance" card, or overview of all the things were were interested in. On one page, for example, I could see the historical state changes of my entities and quickly identify problems, in most cases, by simply looking at the color patterns in the bars. That capability is basically gone without a ton of work. I just thought if it were easy, it would make a lot of people happy. 

Having said that, I suspect a copy/paste of my recorder.yaml entities list would provide most of what I need for a card config and add the necessary bits to finish it off. That is what I'll do. Having to add all the colors will be tedious, but I understand the issues you face with mixing manual with auto in that case.

I do appreciate what you've done here and for sharing it with us. I know it's a lot of work and sometimes it feels like we don't appreciate it because we keep asking for MORE! But that's only because you guys continue to show us _what is possible_.

Cheers!
Shane

**Comment by GrizzlyAK** [comment]
I currently have 162 entities listed in my recorder.yaml file (as a yaml list, just like in your config, but with comments), and I chose to use only _includes_, without wildcards, which gives me complete and unambiguous control over what I'm seeing. This, I think, would be the simplest to implement if we simply copied our recorder.yaml file to the `\www` folder in config, which I believe you'd have access to, since it is basically the same entities list you use in your card config. I'm not sure that would work for all configurations, thought. Details of the different possible configurations in both recorder.yaml and history.yaml, and their interaction, as you probably already know, are [here](https://www.home-assistant.io/integrations/recorder).

Regarding the color, I read your response to someone as it being more difficult, but for me, colors don't matter as long as they make the different entities discernible on the same chart. Previously, I could glance at a row of bar charts that had green for on and red for off (or vice versa), and that would, in an instant, give me all the information I needed. Like, has this sensor been on in the last 14 days? Has the power gone off during that time, etc. I can get all of that same information using the current HA History implementation, it's just harder, requires more effort and thought, and is much, much slower. I don't even use History in HA anymore as a result, which is a giant loss for me.

It would _not_ be difficult for ME to create a manual config to use your card as is, but it might be more difficult for others who use wildcards, or both history and recorder, and complex combinations of include/exclude. They would benefit more from any changes you made in that direction, and I'm sure would be greatly appreciated.

**Comment by alexarch21** [comment]
> to the \www folder in config, which I believe you'd have access to
_Technically_ client side code can indeed access any internet exposed resource and the `www` folder is. But doing this comes with a slew of security implications and will raise all kinds of red flags in modern browsers. So that's a can of worms I'd rather not open. This card, like pretty much all frontend cards, communicate with HA over a Websocket and/or REST API. There's no access to any files on your server. Things like entity lists, states, history, etc are all accessed over the API. And the frontend code is limited to what the HA core devs expose in that API. 

So for now the only YAML accessible to the card is the one from the frontend configuration. You can however use the `!include` directive to link the frontend config to an external dedicated YAML for history.

> Regarding the color, I read your response to someone as it being more difficult
Well, hacking in the feature itself is not difficult. Making it work in a reliable, intuitive and future proof way is difficult. Especially when mixing it with manually defined colors. And people _will_ mix them.

That said, I _do_ see the potential advantages of adding auto colors to YAML entities. I'll brainstorm this a little over the weekend and see what I can come up with.

**Comment by alexarch21** [comment]
Automatic colors for line graphs defined in the YAML are now available in V 1.0.26.

**Comment by GrizzlyAK** [comment]
Fantastic! I'm going to see what kind of trouble I can get into. ;-)
