### ISSUE TITLE
Export CSV not working as expected

### ISSUE THREAD

**Issue by ronniebach** [alexarch21/history-explorer-card#68]
When clicking export to csv - all raw data seems to get exportet.
It doesn't stick to the selected data resolution - for examle - I I select Hour - I would expect the export to only have 1 entry per hour - and not every single logged value within this hour.

It should reflect the data that is visualized.

**Comment by alexarch21** [comment]
The CSV will export the raw unprocessed data over the displayed time range. This is expected behavior. The card will not touch the data it exports.

As for total_increasing entities (and for those only), an option to export processed values could indeed be useful. But like most people writing OS software in their free time, I have to prioritize things. Feel free to submit a PR with the missing feature, I'd be happy to add it to the card.
