### ISSUE TITLE
FR: long-term statistics period

### ISSUE THREAD

**Issue by ondras12345** [alexarch21/history-explorer-card#91]
Hi, thanks for the new long-term statistics support.

It would be nice if it was possible to query 5minute long-term statistics instead of the default 1 hour period.
This is how apexcharts-card does it: [API call](https://github.com/RomRider/apexcharts-card/blob/35fc100b90f70281fad7ff1003734186aa35ce99/src/graphEntry.ts#L463-L471); [possible values](https://github.com/RomRider/apexcharts-card/blob/35fc100b90f70281fad7ff1003734186aa35ce99/src/types-config.ts#L64).

I believe this line would need to be changed
https://github.com/alexarch21/history-explorer-card/blob/fb0de39129d7096acb1c99181b1d04238c94596d/src/history-explorer-card.js#L1458
(as well as the same call in [CSV export](https://github.com/alexarch21/history-explorer-card/blob/fb0de39129d7096acb1c99181b1d04238c94596d/src/history-csv-exporter.js#L148)) to use a value supplied in the config instead of the string literal `"hour"`.

**Comment by alexarch21** [comment]
Correct, I chose hourly sample points because they were a good balance between precision and rendering performance. I originally tried going down to 5 minutes, when zooming out massively, data decimation would have to kick in much harder to keep interactive rendering speeds due to the amount of data points over something like 6 months.

I guess I could make the period configurable.

**Comment by ondras12345** [comment]
Or maybe set CSV export to 5 minutes since performance shouldn't matter too much during that operation.
That would be enough for my use case, but I can imagine some people would find 5 minute intervals in visualization useful.

**Comment by alexarch21** [comment]
Even for CSV export it would be optional, default would be an hour. Exporting something like 6 months with 5 minute resolution creates a huge amount of data points. More than 52k points (rather than 4k for hour resolution). Now imagine doing this for multiple sensors. You'll end up with a spreadsheet with several 100k rows...

And most of the time, the original sensor data won't even have 5 minute resolution anyway, so the LTS samples are interpolated.

As far as I see it, 5 minute LTS is complete overkill for the majority of users. For the few specific cases where it makes sense, enabling it should be an option, but not the default.

**Comment by alexarch21** [comment]
After more investigation, this will not be possible for 5 minute intervals, due to internal limitations of the HA history API, which is unable to retrieve more than a couple of weeks of statistics data with 5 minute resolution. The native HA statistical graphs are also affected (try one with 5 minute period, over 365 days, you will notice the data doesn't go further back than a few weeks. Switching to hour period will show the entire year). 

The next card release will have configurable periods for hour, day, month. While it will be possible to ask for 5 minute interval, the results will not cover the entire requested time frame and as such, this value will be unsupported.
